version: "{build}"
clone_folder: "C:\\WORK"

environment:
  global:
    CABAL: "cabal --store-dir=C:\\SR --http-transport=plain-http"
    HC: "ghc"
    TEST: "--enable-tests"
    NOTEST: "--disable-tests"
    BENCH: "--enable-benchmarks"
    NOBENCH: "--disable-benchmarks"
  matrix:
    # We don't get many build bots with Appveyor so we only include the
    # latest for each major version.
    - GHC_VERSION: "8.0.2"
    - GHC_VERSION: "8.2.2"
    - GHC_VERSION: "8.4.4"
    - GHC_VERSION: "8.6.4"

cache:
 - "C:\\SR"

install:
 - "choco install -y ghc --version %GHC_VERSION%"
 - "refreshenv"
 - "%CABAL% --version"
 - "%HC% --version"
 - "%CABAL% v2-update"
 - "%CABAL% v2-build -w %HC% %TEST% %BENCH% --dep -j2 all"
 - "%CABAL% v2-build -w %HC% %NOTEST% %NOBENCH% --dep -j2 all"

build: off

# test_script mostly transcribed from .travis.yml
test_script:
 # show project file
 - "cat cabal.project || true"

 # this builds all libraries and executables (without tests/benchmarks)
 - "%CABAL% v2-build --disable-tests --disable-benchmarks all"

 # build & run tests, build benchmarks
 - "%CABAL% v2-build -w %HC% %TEST% %BENCH% all"
 - "%CABAL% v2-test -w %HC% %TEST% %BENCH% all"

 # haddock
 - "%CABAL% v2-haddock -w %HC% %TEST% %BENCH% all"
