name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - edited

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:    [macos-latest, ubuntu-latest, windows-latest]
        cabal: ["3.8.1.0"]
        ghc:   ["8.0.2", "8.2.2", "8.4.4", "8.6.5", "8.8.4", "8.10.7", "9.2.4", "9.4.1"]
        exclude:
          # https://github.com/haskell/text/pull/404
          - os: windows-latest
            ghc: "8.0.2"
          - os: windows-latest
            ghc: "8.2.2"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Cabal Update
        run: |
          cabal v2-update
          cabal v2-freeze $CONFIG
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-
      - name: Build all
        run: |
          cabal build all
          cabal sdist all
      - name: Run tests
        run: |
           cabal test all
      - name: Build haddock
        run: |
          cabal haddock all
